name: hifinn_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78
  - faiss-cpu=1.8.0
  - lightning=2.3.0
  - networkx=3.2.1
  - numpy=1.26.4
  - pip=24.0
  - python=3.12.4
  - pytorch=2.6.0
  - pytorch-lightning=2.0.3
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=69.5.1
  - torchmetrics=1.4.0.post0
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - pip:
      - fair-esm==2.0.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0