input: ./ModelData/cluster30_seqs_missing_ec_removed.fasta # what we want to annotate
k: 20 # number of nearest neighbours
id_to_annotation: ./ModelData/swissprot_all_ec_nums.json # id to annotation file, to map hits to EC's
model_path: ./ModelData/swissprot_reduced30_epoch_150.ckpt
ids: ./ModelData/reduced30_ckpt150_sorted_ids.json # the ids pertaining to the entries of our vector index
index: ./ModelData/reduced30_ckpt150.index # faiss vector index file
output_path: ./price_annos.json # where we want to save our annotations to
distance_cutoff: 1.0 
device: 'cpu'
return_distance: True
return_confidence: True